query Articles($isPublished: Boolean) {
  articles(isPublished: $isPublished) {
    count
    rows {
      id
      title
      outline
      body
      isPublished
      lastPublishedAt
      createdAt
      updatedAt
    }
  }
}
