name: Deploy frontend

on:
  push:
    branches:
      - master

env:
  TAG: eu.gcr.io/${{ secrets.GCP_PROJECT }}/blog-frontend:latest
  SERVICE_NAME: blog-frontend
  REGION: europe-west4
  PORT: 80

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCP_RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_RUN_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure docker via Google Cloud auth
        run: |
          gcloud auth configure-docker

      - name: Build the Docker image
        run: |
          docker build -t $TAG .

      - name: Push the Docker image to Google Container Registry
        run: |
          docker push $TAG

      - name: Deploy image to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --region="$REGION" \
            --quiet \
            --image="$TAG" \
            --platform="managed" \
            --port="$PORT" \
            --allow-unauthenticated
